### ISSUE TITLE
Web共有サイトにおけるファイル読み込みに関する質問

### ISSUE THREAD

**Issue by theta04** [kou-yeung/kuromoji_webgl#4]
お世話になっております。
件のクイズゲーム開発をしているthetaと申します。
WebGL向けのサンプルシーンのご提供、大変感謝しております。
おかげさまで、ローカル環境においては正常に動作することが確認できました。ありがとうございます。

しかし、unityroomとplicyにアップロードして実行した際に、
ビルドに含まれるkuromojiフォルダが読み込めない問題が発生しました。
GitHubのページ最下部にある「unityroomでの使用について」にも言及があるのは確認しましたが、
改めてご質問させていただきます。

kuromojiフォルダ内のkuromoji.jsや辞書ファイルは、
「外部(自前)のサーバーから読み込む必要がある」という認識で正しいでしょうか？

初歩的な質問で申し訳ありませんが、ご教示いただければ幸いです。

**Comment by kou-yeung** [comment]
はい、例えば

[demo](https://unityroom.com/games/kuromoji_webgl) では

github.io にアップしたファイルを使ってます

```
// 初期化
takuyaa.kuromoji.LoadScript("https://kou-yeung.github.io/kuromoji_webgl/kuromoji/build/kuromoji.js");
```

```
// 解析
takuyaa.kuromoji.Kuromoji.Build("https://kou-yeung.github.io/kuromoji_webgl/kuromoji/dict/", "すもももももももものうち", res =>
{
    foreach (var item in res)
    {
        Debug.Log(item.surface_form);
    }
});
```

の状態でビルドしています。
（上記のURLで試してみて、動作したらご自身の github.io あるいは ファイルサーバに差し替えれば動くと思います

**Comment by kou-yeung** [comment]
![image](https://github.com/kou-yeung/kuromoji_webgl/assets/7277282/140caaa0-f3c3-44ed-8462-0bdfd4eab565)

github.io は上記のように配置してます

**Comment by theta04** [comment]
github.ioにkuromojiと辞書を配置して読み込む方法が
うまくいかなかったことをご報告いたします。

>  // kuromoji.jsはこのように初期化処理を行っております。
>     void Start()
>     {
>         takuyaa.kuromoji.Kuromoji.LoadScript("https://theta04.github.io/qb5kuromoji/kuromoji.js");
>     }

やはり、AWSやFirebaseなどの自前のサーバーを用意した方が確実でしょうか？
質問ばかりで申し訳ありません。

**Comment by kou-yeung** [comment]
`Kuromoji.LoadScript("https://theta04.github.io/qb5kuromoji/kuromoji.js");`

```
Kuromoji.Build("https://theta04.github.io/qb5kuromoji/dict/", text, res =>
{
    //...
}
```

上記の設定で unityroom では動作することを確認しました

たぶんですが、ローカル環境(localhost)で実行時外部ドメイン(今回は ~.github.io) へアクセスできないと思います
※コンソールに「Cross-Origin-Resource-Policy」エラー表示されたはず

**Comment by kou-yeung** [comment]
localhost 実行時にビルドパス内のファイルを使えば解決できると思います
Application.absoluteURL を使って実行してるURL取得できます

以下サンプル ( unityroom で動作確認済 )
```
if (Application.absoluteURL.Contains("localhost"))
{
    Kuromoji.LoadScript();
}
else
{
    Kuromoji.LoadScript("https://theta04.github.io/qb5kuromoji/kuromoji.js");
}
```

```
Action<Kuromoji.Tokenize[]> cb = (res) =>
{
    //... 解析結果
}

if (Application.absoluteURL.Contains("localhost"))
{
     Kuromoji.Build(text, cb);
}
else
{
    Kuromoji.Build("https://theta04.github.io/qb5kuromoji/dict/", text, cb);
}
```

**Comment by theta04** [comment]
わあ、ありがとうございます！
試してみます！

**Comment by theta04** [comment]
ご提供いただいたサンプルシーンを用いて、「unityroom」での動作を確認しました！
ありがとうございます！！
これであとはクイズゲームに組み込むだけです。

「PliCy」のほうは、
>Failed to load resource: net::ERR_BLOCKED_BY_RESPONSE.NotSameOriginAfterDefaultedToSameOriginByCoep

起動時に上記のエラーが発生して、kuromoji.jsを読み込むことが叶いませんでした。
(素人ながら推測するに、PliCyのサーバーのセキュリティが堅いのでしょうか？)

p.s.
初歩的な質問を重ねて、お時間を取らせるわけにはいかないと思い、
自己解決することに固執していました。

こんな簡単に解決するならば、すぐに質問しておくべきでしたね。
お力添え本当にありがとうございました。

**Comment by kou-yeung** [comment]
plicy のアカウント登録してアップしてみた

plicy は フォルダごと zip してアップするので、
外部ドメインアクセスは厳しいが、unityroom と異なって
指定された4つのファイル( data.gz / framework.js.gz / loader.js / wasm.gz ) 以外も展開してくれます

なので、

```
if (Application.absoluteURL.Contains("localhost") {}
↓
if (Application.absoluteURL.Contains("localhost") || Application.absoluteURL.Contains("plicy.net"))
{
    Kuromoji.LoadScript();
}
else
{
    //...
}
```
※解析結果 のほうも合わせて調整してね～

上記のように調整して plicy.net も相対パスにあるものを使えばいいです（動作確認済 [demo](https://plicy.net/GamePlay/181236)

**Comment by kou-yeung** [comment]
ビルドの出力フォルダを丸ごと zip するので、
ビルドフォルダに 複製した kuromoji も含まれてるから
同じドメイン内に展開され、クロスドメイン制約は解消されます～

**Comment by theta04** [comment]
おお、そんなことでplicyの方は解決できるんですね！
やってみます！ありがとうございます！

**Comment by theta04** [comment]
おかげさまで、unityroom・plicyの両プラットフォームにて、
kuromojiの実装に成功しました！

kouさんのお力添えがなければ、とっくに諦めていたことです。
本当に助かりました！ありがとうございます！

また、お時間が許すようでしたら、是非ともプレイしていただけると嬉しいです！
unityroom
https://unityroom.com/games/qbf_a01
plicy
https://plicy.net/GamePlay/179782

**Comment by kou-yeung** [comment]
対応できてよかったです！(*'▽')ﾉ
